q1
natural language processing is a sub field of ai . That helps computers to understand and generate human languages . it transforms text into numerical representation so that machines can understand the human languages .

q2
NLP does some steps of text cleaning , preprocessing , tokenization and embedding techniques so that the machines can understand human languages in terms of numbers. chatbots takes prompt as input (internally they convert prompt into tokens , embeddings and preprocess those embeddings and generate the respective answer).

1. Spam Detection: Identifies unwanted emails by analyzing text for suspicious patterns.
2. Sentiment Analysis: Determines the emotional tone (positive, negative, neutral) in text data.
3. Machine Translation: Translates text from one human language to another (e.g., Google Translate).
4. Chatbots/Virtual Assistants: Understands and responds to user commands or questions in natural language.

A rule-based NLP system uses predefined linguistic rules or patterns to process text. It doesn't learn from data.
For spam detection, a rule could be: if the word "Congratulations" is in the message, label it as spam.

1. Tokenization: Breaking text into smaller units (words/sentences).
2. Lowercasing: Converting all text to a uniform lowercase format.
3. Stopword Removal: Eliminating common, less meaningful words (e.g., "the", "is").
4. Stemming/Lemmatization: Reducing words to their root form.
5. Part-of-Speech Tagging: Labeling words with their grammatical role.
6. Named Entity Recognition: Identifying proper nouns (people, places, organizations).
7. Dependency Parsing: Analyzing grammatical relationships between words.
8.

Tokenization is the process of splitting text into smaller units called tokens (words, phrases, symbols).
It's necessary because ML models require numerical input, and tokenization breaks text into discrete items that can be converted into numerical representations.

Stopwords are common words that appear frequently but often carry little semantic meaning. Examples: "the", "is", "and".
They are removed to reduce noise and dimensionality in text data, improving efficiency and focus on more important words.

Lowercasing standardizes text, treating words like "Apple", "apple", and "APPLE" as the same token. This prevents the model from treating them as distinct words.
Example: Without lowercasing, "Good" and "good" would be seen as different, leading to inconsistent analysis.

1. Not converting text columns to string type (`.astype(str)`).
2. Misunderstanding `inplace=True` or not reassigning DataFrame modifications.
3. Incorrectly using string methods (`.str.method()`) vs. Python string methods.
4. Forgetting to handle missing values (NaN) before applying text operations.

`=` is for assignment, used to give a value to a variable or column. `==` is for comparison, checking if two values are equal.
Mixing them up causes errors because `df[df['col'] = 'value']` attempts assignment within a boolean indexing context, which is invalid for comparison.

In [3]:
#p1

sentence="I Love Artigicial Intelligence"
print(type(sentence))

<class 'str'>

In [4]:
#p2
print(len(sentence))

30

In [5]:
print(sentence.split())
print(len(sentence.split()))

['I', 'Love', 'Artigicial', 'Intelligence']
4

In [6]:
message="You won free pizza"
if "free" in message:
    print("yes")

yes

In [7]:
message="Congratulations you won nothing"
if "Congratulations" in message:
    print("spam")
else:
    print("not spam")

spam

In [9]:
import pandas as pd
data={
    "review":["amazing phone","bad phone","good phone","worst phone","excellent camera","bad camera"],
    "sentiment":["positive","negative","positive","negative","positive","negative"]
}
df=pd.DataFrame(data)
df

             review sentiment
0     amazing phone  positive
1         bad phone  negative
2        good phone  positive
3       worst phone  negative
4  excellent camera  positive
5        bad camera  negative

In [10]:
print("shape:",df.shape)
print("summary",df.info())

shape: (6, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     6 non-null      object
 1   sentiment  6 non-null      object
dtypes: object(2)
memory usage: 228.0+ bytes
summary None

In [11]:
print("first 5",df.head(5))
print("last five",df.tail(5))

first 5              review sentiment
0     amazing phone  positive
1         bad phone  negative
2        good phone  positive
3       worst phone  negative
4  excellent camera  positive
last five              review sentiment
1         bad phone  negative
2        good phone  positive
3       worst phone  negative
4  excellent camera  positive
5        bad camera  negative

In [12]:
print(df["sentiment"].value_counts())

sentiment
positive    3
negative    3
Name: count, dtype: int64

In [14]:
df["review"]=df["review"].str.lower()
df

             review sentiment
0     amazing phone  positive
1         bad phone  negative
2        good phone  positive
3       worst phone  negative
4  excellent camera  positive
5        bad camera  negative

In [16]:
df["Length"]=df["review"].apply(len
)
df

             review sentiment  Length
0     amazing phone  positive      13
1         bad phone  negative       9
2        good phone  positive      10
3       worst phone  negative      11
4  excellent camera  positive      16
5        bad camera  negative      10

In [17]:
for rev in df["review"]:
    print(rev)

amazing phone
bad phone
good phone
worst phone
excellent camera
bad camera

In [19]:
print(df[df["review"].str.contains("phone")])

          review sentiment  Length
0  amazing phone  positive      13
1      bad phone  negative       9
2     good phone  positive      10
3    worst phone  negative      11

In [21]:
print(df[df['sentiment']=="positive"])

             review sentiment  Length
0     amazing phone  positive      13
2        good phone  positive      10
4  excellent camera  positive      16

In [22]:
df["Characters"]=df["review"].apply(len
)
df

             review sentiment  Length  Characters
0     amazing phone  positive      13          13
1         bad phone  negative       9           9
2        good phone  positive      10          10
3       worst phone  negative      11          11
4  excellent camera  positive      16          16
5        bad camera  negative      10          10

In [24]:
df["Words"]=df["review"].apply(lambda x :len(x.split()))
df

             review sentiment  Length  Characters  Words
0     amazing phone  positive      13          13      2
1         bad phone  negative       9           9      2
2        good phone  positive      10          10      2
3       worst phone  negative      11          11      2
4  excellent camera  positive      16          16      2
5        bad camera  negative      10          10      2

In [26]:
data = {
    'Review': [
        "An absolute masterpiece! The acting was phenomenal and the plot kept me on the edge of my seat.",
        "Such a waste of time. The plot was predictable and the characters were incredibly boring.",
        "It was an okay movie. Not the best I've seen, but it had a few entertaining moments.",
        "Visually stunning and emotionally gripping. I would highly recommend this film to everyone.",
        "Terrible directing and awful dialogue. I almost walked out of the theater halfway through.",
        "A decent popcorn flick. The action sequences were great, even if the story felt a bit weak."
    ],
    'Sentiment': ['Positive', 'Negative', 'Neutral', 'Positive', 'Negative', 'Neutral']
}

df = pd.DataFrame(data)
print(df[df["Sentiment"]=="Negative"])

                                              Review Sentiment
1  Such a waste of time. The plot was predictable...  Negative
4  Terrible directing and awful dialogue. I almos...  Negative

In [30]:
df["count"]=df['Review'].apply(len)
print(df["count"].max())

95

In [31]:
print(df["Sentiment"].value_counts())

Sentiment
Positive    2
Negative    2
Neutral     2
Name: count, dtype: int64

In [32]:
comments = [
    "The teacher explained the concepts very clearly and was always helpful.",
    "I really enjoyed the interactive activities during the class.",
    "The course material was well-organized and easy to follow.",
    "Great pacing and excellent support from the instructor.",
    "I learned a lot and feel much more confident with the subject.",
    "The classes were too fast-paced and I could not keep up.",
    "I found the assignments extremely confusing and frustrating.",
    "Lack of communication from the professor made this course difficult.",
    "The lectures were boring and did not keep my attention.",
    "I did not receive helpful feedback on my graded submissions."
]


labels = ["Positive", "Positive", "Positive", "Positive", "Positive", 
          "Negative", "Negative", "Negative", "Negative", "Negative"]

df=pd.DataFrame(data)
print("first 5:",df.head(5))
print("last 5:",df.tail(5))

first 5:                                               Review Sentiment
0  An absolute masterpiece! The acting was phenom...  Positive
1  Such a waste of time. The plot was predictable...  Negative
2  It was an okay movie. Not the best I've seen, ...   Neutral
3  Visually stunning and emotionally gripping. I ...  Positive
4  Terrible directing and awful dialogue. I almos...  Negative
last 5:                                               Review Sentiment
1  Such a waste of time. The plot was predictable...  Negative
2  It was an okay movie. Not the best I've seen, ...   Neutral
3  Visually stunning and emotionally gripping. I ...  Positive
4  Terrible directing and awful dialogue. I almos...  Negative
5  A decent popcorn flick. The action sequences w...   Neutral